### ISSUE TITLE
Multiple "HMR ..." console outputs if >1 file in webpack.config.js entry

### ISSUE THREAD

**Issue by rublev** [survivejs/webpack_react#401] opened 2016-05-20 21:10 UTC
For every entry I get an extra line of identical console output. I'm not sure if this is desired output, and if it is, why is it desired?

https://github.com/eveo/webpack-config-test

**webpack.config.js**

	entry: {
		app: PATHS.app,        // app/index.js
		style: PATHS.style,    // app/main.css
		test: PATHS.test       // app/test.css
	}
on initial load and reloads:

![image](https://cloud.githubusercontent.com/assets/470273/15442391/dc683a6c-1eae-11e6-9114-cbd8fd1e84a2.png)

when i clear the console and network panel and hit record, then make a change to `app/index/js`, the bundle is regenerated but nothing is logged in the network, i only see the following in chrome:

![image](https://cloud.githubusercontent.com/assets/470273/15442447/3a93644a-1eaf-11e6-9bd6-4b398fea9a3c.png)

after running the demo at https://github.com/survivejs-demos/webpack-demo the console outputs the same as above, except only two statements because there are two entries.

**Comment by bebraw** [comment] 2016-05-24 05:45
Commented at https://github.com/webpack/webpack/issues/2527 . Based on webpack-dev-server code it seems to create a server/client pair for each `entry`.

Given that seems to be the expected behavior it's probably safe to close this now. Thanks for bringing this up, though, as I was curious about this too. Initially I thought this might be a bug but apparently it's not.

**Closed by bebraw** 2016-05-24 05:45 UTC
