### ISSUE TITLE
Testing React* -

### ISSUE THREAD

**Issue by yosit** [survivejs/webpack_react#256] opened 2015-09-30 05:52 UTC
Hi,
I didn't manage to produce the same result with npm test like you add test.
And when adding the second test it failed running complaining about 'karma start'
I tried to compare your repo with mine to see if there is something strange but besides different versions of your npm modules I didn't see anything.

My folder including everything I have is at: https://www.dropbox.com/s/a28sccgc76zq9nj/kanban_app.zip?dl=0

I also noticed you are missing the --save-dev for the latest npm install for the testing stuff.

Hopefully this would help you to figure out what is missing from the instructions to be able to complete the book.

Awesome book BTW, I was happy to purchase.

**Comment by bebraw** [comment] 2015-09-30 06:52
Hi @yosit,

Great to hear you've found the book useful.

I can see a Karma configuration related issue at your code. Make sure you have it set up like this:

```
		reporters: [
		// Reference: https://github.com/mlex/karma-spec-reporter // Set reporter to print detailed results to console 'spec',
		'spec',
		// Reference: https://github.com/karma-runner/karma-coverage // Output code coverage files
		'coverage'
		],
		files: [
		// Reference: https://www.npmjs.com/package/phantomjs-polyfill
					'node_modules/phantomjs-polyfill/bind-polyfill.js',
		// Needed because React.js requires bind and phantomjs does not support it 'node_modules/phantomjs-polyfill/bind-polyfill.js',
		      // Grab all files in the tests directory that contain _test.
		      'tests/**/*_test.*'
		],
```

Especially that `'node_modules/phantomjs-polyfill/bind-polyfill.js'` is important and it feels like that's the root cause. I noticed you also need to hit `npm install babel --save-dev` because we use `require('babel/register')` at Karma config.

I added that missing `--save-dev` to my development vesion. This will be included to the next edition of the book. I am also dropping *webpack.config.babel.js* in it so we'll get a configuration that's a notch simpler.

Let me know how it goes.

**Comment by yosit** [comment] 2015-09-30 07:10
Awesome, it now works.
I understand now why it happened - I was copying and pasting and for some
reason the formatting from the book is not being kept when pasting.
The missing lines in karma got appended to the comment.

On Wed, Sep 30, 2015 at 9:52 AM, Juho Vepsäläinen <notifications@github.com>
wrote:

> Hi @yosit <https://github.com/yosit>,
>
> Great to hear you've found the book useful.
>
> I can see a Karma configuration related issue at your code. Make sure you
> have it set up like this:
>
>         reporters: [
>         // Reference: https://github.com/mlex/karma-spec-reporter // Set reporter to print detailed results to console 'spec',
>         'spec',
>         // Reference: https://github.com/karma-runner/karma-coverage // Output code coverage files
>         'coverage'
>         ],
>         files: [
>         // Reference: https://www.npmjs.com/package/phantomjs-polyfill
>                     'node_modules/phantomjs-polyfill/bind-polyfill.js',
>         // Needed because React.js requires bind and phantomjs does not support it 'node_modules/phantomjs-polyfill/bind-polyfill.js',
>               // Grab all files in the tests directory that contain _test.
>               'tests/**/*_test.*'
>         ],
>
> Especially that 'node_modules/phantomjs-polyfill/bind-polyfill.js' is
> important and it feels like that's the root cause. I noticed you also need
> to hit npm install babel --save-dev because we use
> require('babel/register') at Karma config.
>
> I added that missing --save-dev to my development vesion. This will be
> included to the next edition of the book. I am also dropping
> *webpack.config.babel.js* in it so we'll get a configuration that's a
> notch simpler.
>
> Let me know how it goes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/survivejs/webpack_react/issues/256#issuecomment-144306741>
> .
>



-- 

Yosi Taguri | Founder & CTO | Yallo Inc. | https://yallo.com | Mobile:
+972-54-4816020 | Email: yosi@yallo.com

**Comment by bebraw** [comment] 2015-09-30 07:24
Ok, great to hear you got it working. Perhaps there is something I can do about that copy/paste thing (shorter comment?). I'll close this after I've tried that.

**Comment by yosit** [comment] 2015-09-30 07:29
Yes. A few things:
1. drop the numbering - copy and paste from ebook / pdf  will carry the
numbers.
2. on the web you can use a widget to help copy and paste the stages.

On Wed, Sep 30, 2015 at 10:24 AM, Juho Vepsäläinen <notifications@github.com
> wrote:

> Ok, great to hear you got it working. Perhaps there is something I can do
> about that copy/paste thing (shorter comment?). I'll close this after I've
> tried that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/survivejs/webpack_react/issues/256#issuecomment-144312501>
> .
>



-- 

Yosi Taguri | Founder & CTO | Yallo Inc. | https://yallo.com | Mobile:
+972-54-4816020 | Email: yosi@yallo.com

**Comment by bebraw** [comment] 2015-09-30 11:09
Yeah. 1. will help so line numbers will be disabled in the next edition. I'll do 2. later. Thanks!

**Closed by bebraw** 2015-09-30 11:09 UTC
