### ISSUE TITLE
Setting Up Webpack - Feedback and Suggestion

### ISSUE THREAD

**Issue by saviomuc** [survivejs/webpack_react#357] opened 2016-02-16 12:36 UTC
Currently I am in the process of rereading the Webpack part because I started to look for a simpler approach to bundling and building (first experimenting with npm only instead of gulp but hit a wall soon). In the process I read a lot of tutorials and experimented with some ways to structure Webpack. 

**Lacking explanation of Webpack**
What I liked about your introduction was the 'Webpack Compared' part. It really helped me understand where Webpack is coming from and what kind of problem it is supposed to solve. This however only applies to the first paragraph ([...] Webpack takes a more monolithic approach [...]). You then follow up in the second paragraph with "The loader mechanism ensures [...]" without explaining the concept of loaders and plugins. I think it would be great to have a short sentence on both concepts as they are quite important to understand how Webpack works. A short link to a resource like [loaders](https://webpack.github.io/docs/loaders.html) would also be great in case the reader wants to know more. 
Also you say something about `require.ensure`. I feel this information is not important for the reader to understand the difference between Webpack and other options.

**Too bloated Webpack config for tutorial**
I didn't finish your book yet. Currently I am jumping back and forth between various books from the React Indiebundle to get a better understanding of fundamental React Concepts. But I feel that the Webpack Config set up for the example project is a little bit overengineered. For instance you set up multiple targets for Webpack. As a result you need to load another dependency `webpack-merge`. I feel that 
1. there must be another "standard' way to do it. For instance [react-start](https://github.com/webpack/react-starter) has sort of a common config and different targets. I can understand though that it is too verbose at this point and completely overengineered. 
2. it makes the config too bloated. I suggest to ditch the various build targets at this point and move to a appendix. This would be the more logical solution. You would focus on what is absolutely necessary and the interested reader can read more about various deployment/build strategies for webpack in the appendix. 

Please don't get me wrong. This chapter helped me move to webpack. I absolutely love it. I just feel it could be clearer and more condensed.

**Comment by bebraw** [comment] 2016-02-16 14:02
> Lacking explanation of Webpack
> ...

Thanks for pointing this out. I'll beef it up. :smile:

> Too bloated Webpack config for tutorial
> ...

The problem is that there isn't one "right" way to configure webpack. The current solution I'm showcasing was developed for the purposes of the book and since then it has found its use in my own projects.

Even though `webpack-merge` adds a bit of complexity, the approach works pretty neatly when you set up a build or a test target. Without it you would end up with separate files and convoluted file structure like in that `react-start` project.

That said, I agree it's a heavy way to start a book. One way to solve the issue would be simply to split the book in two and provide a ready made starting point for the React book. I could rework the old Webpack cookbook during this effort.

On a related note, I've been developing something like Babel presets for Webpack. See [webpack-presets](https://github.com/survivejs/webpack-presets). This is more of a tool for my personal purposes at the moment, though.

> Please don't get me wrong. This chapter helped me move to webpack. I absolutely love it. I just feel it could be clearer and more condensed.

No worries. I appreciate this sort of feedback as it allows me to rethink things. At the moment splitting up the book would seem like the strongest option even if it would take quite heavy amount of work. Perhaps there are some intermediate steps I could take.

**Comment by saviomuc** [comment] 2016-02-17 11:17
Hi, I think they general structure is spot on.

A proper build process is as much important as development itself. It's part of the development experience. And webpack is a natural fit to React and ES6 in that matter. One of the biggest problems for me, when I started with React, was: "How do I set up an environment which makes React development fun to use?". Webpack helps creating an environment which makes React development fun.

However a reader and learner should be in full control of his learning environment. It makes sense to completely start from scratch. It's also fine it that approach is opinionated. It's just that the "heavy start" takes a little bit away from the fun and introduces a bit of overhead. 

I see where you are coming from when you point out to the starting point in `How to approach the book`. But for me it would be an unsatisfying approach because I would feel that I miss some foundation. I want to control and understand my development environment. It is perfect for somebody already experienced with webpack though.

My suggestion to solve it:
- Introduce Webpack and have a basic build including all what is need for the book projects
- Refer to an appendix for more sophisticated builds including build targets. That would also be an excellent entry point to refer to your webpack cook book.

**Comment by bebraw** [comment] 2016-02-17 11:26
> * Introduce Webpack and have a basic build including all what is need for the book projects
> * Refer to an appendix for more sophisticated builds including build targets. That would also be an excellent entry point to refer to your webpack cook book.

I like this idea a lot. It would definitely push complexity to the right place while making the early part of the book lighter.

I'll try to prototype something for you to have a look at. :+1:

**Comment by bebraw** [comment] 2016-02-27 09:15
@saviomuc I've made some indirect progress on this. We are currently moving the webpack cookbook below survivejs. Here's [a sneak peek](http://survivejs.com/webpack/introduction/). The content needs a lot of work obviously, but the groundwork is there (styling, structure).

I will test drive [kotatsu](https://github.com/Yomguithereal/kotatsu) soon. Kotatsu is a simple webpack wrapper essentially. Assuming the test goes well, I'll integrate it to the React book. The webpack content will go to the webpack one. Current readers will get this new book for free.

The greatest benefit of this move is that it gets rid of some of the bloat webpack brings to the current book and we'll get two more focused ones. You might want to learn one without the other after all.

**Comment by saviomuc** [comment] 2016-02-27 13:28
@bebraw Thank you! I will take a look. Do you need some feedback? I guess you are still working on a lot of content. Kotatsu looks interesting. I can imagine that it can help setting up a working environment from scratch while still keeping the 'feel of control' over the environment. It seems like a good compromise and I like the idea.

**Comment by bebraw** [comment] 2016-02-27 13:31
@saviomuc No need for feedback yet. The content needs some heavy work. :smile:

I'll let you know when it's in decent shape. Compared to the React book, it's going to be more recipe oriented (smaller chapters).

Kotatsu is nice in that you should still be able to use your webpack knowledge with it. I am in good terms with the author so even if there are some features missing, we can likely get them done without much trouble.

**Comment by saviomuc** [comment] 2016-02-27 13:35
Great! 👍 Looking forward to it!

**Comment by bebraw** [comment] 2016-04-03 17:31
First part done. There's a [separate book](http://survivejs.com/webpack/introduction/) now. I'll do a minor update on this book and then perform restructuring needed so this needs to remain open. :+1:

**Comment by bebraw** [comment] 2016-05-15 07:43
@saviomuc The [webpack book](http://survivejs.com/webpack/introduction) is fairly stable now. I'll obviously grow it and improve it further. If you have time to have a quick look, that would be great. 👍 

I'm closing this issue as the `dev` version doesn't contain the chapter in question anymore as it has been split up and discussed in far greater detail over there. 😄

**Closed by bebraw** 2016-05-15 07:43 UTC

**Comment by saviomuc** [comment] 2016-05-17 05:55
Thanks. This week I am actually working on setting up a new project with webpack. So this will come in handy. Will provide feedback soon =)
